export const APP_ID         = `thramcss`;
export const ROOT_VIEW      = 'home';
export const NOT_FOUND_VIEW = 'not-found';
export const PARAMS_REG_EXP = '%\{(.*?)\}'; // 3 secs
export const ASSETS_URL     = '/assets'; // 3 secs
export const IMAGES_URL     = `${ASSETS_URL}/images`; // 3 secs
export const AUDIOS_URL     = `${ASSETS_URL}/audios`; // 3 secs
export const VIDEOS_URL     = `${ASSETS_URL}/videos`; // 3 secs
export const SUB_PAGES_URL  = `${ASSETS_URL}/subpages`; // 3 secs